// Ordinarily, you'd generate this data from markdown files in your
// repo, or fetch them from a database of some kind. But in order to
// avoid unnecessary dependencies in the starter template, and in the
// service of obviousness, we're just going to leave it here.

// This file is called `_posts.js` rather than `posts.js`, because
// we don't want to create an `/blog/posts` route — the leading
// underscore tells Sapper not to do that.

const posts = [
	{
		"title": 'Blogpost 1',
		"html": '<p>1111 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-1',
		"createdAt": '2020-06-22T04:36:26.000+00:00',
		"id": '1',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 2',
		"html": '<p>2222 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-2',
		"createdAt": '2020-06-22T04:37:26.000+00:00',
		"id": '2',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 3',
		"html": '<p>3333 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-3',
		"createdAt": '2020-06-22T04:38:26.000+00:00',
		"id": '3',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 4',
		"html": '<p>4444 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-4',
		"createdAt": '2020-06-22T04:38:26.000+00:00',
		"id": '4',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 5',
		"html": '<p>5 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-5',
		"createdAt": '2020-06-22T04:36:26.000+00:00',
		"id": '5',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 6',
		"html": '<p>6222 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-6',
		"createdAt": '2020-06-22T04:37:26.000+00:00',
		"id": '6',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 7',
		"html": '<p>7777 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-7',
		"createdAt": '2020-06-22T04:78:26.000+00:00',
		"id": '7',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 8',
		"html": '<p>4444 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-8',
		"createdAt": '2020-06-22T04:38:26.000+00:00',
		"id": '8',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 9',
		"html": '<p>1111 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-9',
		"createdAt": '2020-06-22T04:36:26.000+00:00',
		"id": '1',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 10',
		"html": '<p>2222 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-10',
		"createdAt": '2020-06-22T04:37:26.000+00:00',
		"id": '2',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 11',
		"html": '<p>3333 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-11',
		"createdAt": '2020-06-22T04:38:26.000+00:00',
		"id": '3',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 12',
		"html": '<p>4444 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-12',
		"createdAt": '2020-06-22T04:38:26.000+00:00',
		"id": '4',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 13',
		"html": '<p>1111 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-13',
		"createdAt": '2020-06-22T04:36:26.000+00:00',
		"id": '1',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 14',
		"html": '<p>2222 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-14',
		"createdAt": '2020-06-22T04:37:26.000+00:00',
		"id": '2',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 15',
		"html": '<p>3333 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-3',
		"createdAt": '2020-06-22T04:38:26.000+00:00',
		"id": '3',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 16',
		"html": '<p>4444 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-4',
		"createdAt": '2020-06-22T04:38:26.000+00:00',
		"id": '4',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 17',
		"html": '<p>1111 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-1',
		"createdAt": '2020-06-22T04:36:26.000+00:00',
		"id": '1',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 18',
		"html": '<p>2222 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-2',
		"createdAt": '2020-06-22T04:37:26.000+00:00',
		"id": '2',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 19',
		"html": '<p>3333 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-3',
		"createdAt": '2020-06-22T04:38:26.000+00:00',
		"id": '3',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 20',
		"html": '<p>4444 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-4',
		"createdAt": '2020-06-22T04:38:26.000+00:00',
		"id": '4',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 21',
		"html": '<p>1111 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-1',
		"createdAt": '2020-06-22T04:36:26.000+00:00',
		"id": '1',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 22',
		"html": '<p>2222 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-2',
		"createdAt": '2020-06-22T04:37:26.000+00:00',
		"id": '2',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 23',
		"html": '<p>3333 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-3',
		"createdAt": '2020-06-22T04:38:26.000+00:00',
		"id": '3',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 24',
		"html": '<p>4444 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-4',
		"createdAt": '2020-06-22T04:38:26.000+00:00',
		"id": '4',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 25',
		"html": '<p>1111 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-1',
		"createdAt": '2020-06-22T04:36:26.000+00:00',
		"id": '1',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 26',
		"html": '<p>2222 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-2',
		"createdAt": '2020-06-22T04:37:26.000+00:00',
		"id": '2',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 27',
		"html": '<p>3333 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-3',
		"createdAt": '2020-06-22T04:38:26.000+00:00',
		"id": '3',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
	{
		"title": 'Blogpost 28',
		"html": '<p>4444 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>',
		"slug": 'blogpost-4',
		"createdAt": '2020-06-22T04:38:26.000+00:00',
		"id": '4',
		"desc": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		"tag": 'general',
		"image": 'https://www.teeth22.com/wp-content/uploads/2018/11/cuidados-diferentes-tipos-ortodoncia-1024x511.jpg',
	},
];

posts.forEach(post => {
	post.html = post.html.replace(/^\t{3}/gm, '');
});

export default posts;
